/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace Apache.IoTDB.Service.Rpc.Thrift
{

  public partial class TSInsertRecordsReq : TBase
  {

    public long SessionId { get; set; }

    public List<string> DeviceIds { get; set; }

    public List<List<string>> MeasurementsList { get; set; }

    public List<byte[]> ValuesList { get; set; }

    public List<long> Timestamps { get; set; }

    public TSInsertRecordsReq()
    {
    }

    public TSInsertRecordsReq(long sessionId, List<string> deviceIds, List<List<string>> measurementsList, List<byte[]> valuesList, List<long> timestamps) : this()
    {
      this.SessionId = sessionId;
      this.DeviceIds = deviceIds;
      this.MeasurementsList = measurementsList;
      this.ValuesList = valuesList;
      this.Timestamps = timestamps;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_sessionId = false;
        bool isset_deviceIds = false;
        bool isset_measurementsList = false;
        bool isset_valuesList = false;
        bool isset_timestamps = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64)
              {
                SessionId = await iprot.ReadI64Async(cancellationToken);
                isset_sessionId = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.List)
              {
                {
                  TList _list87 = await iprot.ReadListBeginAsync(cancellationToken);
                  DeviceIds = new List<string>(_list87.Count);
                  for(int _i88 = 0; _i88 < _list87.Count; ++_i88)
                  {
                    string _elem89;
                    _elem89 = await iprot.ReadStringAsync(cancellationToken);
                    DeviceIds.Add(_elem89);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_deviceIds = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.List)
              {
                {
                  TList _list90 = await iprot.ReadListBeginAsync(cancellationToken);
                  MeasurementsList = new List<List<string>>(_list90.Count);
                  for(int _i91 = 0; _i91 < _list90.Count; ++_i91)
                  {
                    List<string> _elem92;
                    {
                      TList _list93 = await iprot.ReadListBeginAsync(cancellationToken);
                      _elem92 = new List<string>(_list93.Count);
                      for(int _i94 = 0; _i94 < _list93.Count; ++_i94)
                      {
                        string _elem95;
                        _elem95 = await iprot.ReadStringAsync(cancellationToken);
                        _elem92.Add(_elem95);
                      }
                      await iprot.ReadListEndAsync(cancellationToken);
                    }
                    MeasurementsList.Add(_elem92);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_measurementsList = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.List)
              {
                {
                  TList _list96 = await iprot.ReadListBeginAsync(cancellationToken);
                  ValuesList = new List<byte[]>(_list96.Count);
                  for(int _i97 = 0; _i97 < _list96.Count; ++_i97)
                  {
                    byte[] _elem98;
                    _elem98 = await iprot.ReadBinaryAsync(cancellationToken);
                    ValuesList.Add(_elem98);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_valuesList = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.List)
              {
                {
                  TList _list99 = await iprot.ReadListBeginAsync(cancellationToken);
                  Timestamps = new List<long>(_list99.Count);
                  for(int _i100 = 0; _i100 < _list99.Count; ++_i100)
                  {
                    long _elem101;
                    _elem101 = await iprot.ReadI64Async(cancellationToken);
                    Timestamps.Add(_elem101);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_timestamps = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_sessionId)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_deviceIds)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_measurementsList)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_valuesList)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_timestamps)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("TSInsertRecordsReq");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "sessionId";
        field.Type = TType.I64;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(SessionId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "deviceIds";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, DeviceIds.Count), cancellationToken);
          foreach (string _iter102 in DeviceIds)
          {
            await oprot.WriteStringAsync(_iter102, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "measurementsList";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.List, MeasurementsList.Count), cancellationToken);
          foreach (List<string> _iter103 in MeasurementsList)
          {
            {
              await oprot.WriteListBeginAsync(new TList(TType.String, _iter103.Count), cancellationToken);
              foreach (string _iter104 in _iter103)
              {
                await oprot.WriteStringAsync(_iter104, cancellationToken);
              }
              await oprot.WriteListEndAsync(cancellationToken);
            }
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "valuesList";
        field.Type = TType.List;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, ValuesList.Count), cancellationToken);
          foreach (byte[] _iter105 in ValuesList)
          {
            await oprot.WriteBinaryAsync(_iter105, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "timestamps";
        field.Type = TType.List;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.I64, Timestamps.Count), cancellationToken);
          foreach (long _iter106 in Timestamps)
          {
            await oprot.WriteI64Async(_iter106, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as TSInsertRecordsReq;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(SessionId, other.SessionId)
        && TCollections.Equals(DeviceIds, other.DeviceIds)
        && TCollections.Equals(MeasurementsList, other.MeasurementsList)
        && TCollections.Equals(ValuesList, other.ValuesList)
        && TCollections.Equals(Timestamps, other.Timestamps);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + SessionId.GetHashCode();
        hashcode = (hashcode * 397) + TCollections.GetHashCode(DeviceIds);
        hashcode = (hashcode * 397) + TCollections.GetHashCode(MeasurementsList);
        hashcode = (hashcode * 397) + TCollections.GetHashCode(ValuesList);
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Timestamps);
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("TSInsertRecordsReq(");
      sb.Append(", SessionId: ");
      sb.Append(SessionId);
      sb.Append(", DeviceIds: ");
      sb.Append(DeviceIds);
      sb.Append(", MeasurementsList: ");
      sb.Append(MeasurementsList);
      sb.Append(", ValuesList: ");
      sb.Append(ValuesList);
      sb.Append(", Timestamps: ");
      sb.Append(Timestamps);
      sb.Append(")");
      return sb.ToString();
    }
  }

}
