/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace Apache.IoTDB.Cluster.Rpc.Thrift
{

  public partial class CheckStatusResponse : TBase
  {

    public bool PartitionalIntervalEquals { get; set; }

    public bool HashSaltEquals { get; set; }

    public bool ReplicationNumEquals { get; set; }

    public bool SeedNodeEquals { get; set; }

    public CheckStatusResponse()
    {
    }

    public CheckStatusResponse(bool partitionalIntervalEquals, bool hashSaltEquals, bool replicationNumEquals, bool seedNodeEquals) : this()
    {
      this.PartitionalIntervalEquals = partitionalIntervalEquals;
      this.HashSaltEquals = hashSaltEquals;
      this.ReplicationNumEquals = replicationNumEquals;
      this.SeedNodeEquals = seedNodeEquals;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_partitionalIntervalEquals = false;
        bool isset_hashSaltEquals = false;
        bool isset_replicationNumEquals = false;
        bool isset_seedNodeEquals = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool)
              {
                PartitionalIntervalEquals = await iprot.ReadBoolAsync(cancellationToken);
                isset_partitionalIntervalEquals = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                HashSaltEquals = await iprot.ReadBoolAsync(cancellationToken);
                isset_hashSaltEquals = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Bool)
              {
                ReplicationNumEquals = await iprot.ReadBoolAsync(cancellationToken);
                isset_replicationNumEquals = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.Bool)
              {
                SeedNodeEquals = await iprot.ReadBoolAsync(cancellationToken);
                isset_seedNodeEquals = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_partitionalIntervalEquals)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_hashSaltEquals)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_replicationNumEquals)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_seedNodeEquals)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("CheckStatusResponse");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "partitionalIntervalEquals";
        field.Type = TType.Bool;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBoolAsync(PartitionalIntervalEquals, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "hashSaltEquals";
        field.Type = TType.Bool;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBoolAsync(HashSaltEquals, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "replicationNumEquals";
        field.Type = TType.Bool;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBoolAsync(ReplicationNumEquals, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "seedNodeEquals";
        field.Type = TType.Bool;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBoolAsync(SeedNodeEquals, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as CheckStatusResponse;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(PartitionalIntervalEquals, other.PartitionalIntervalEquals)
        && System.Object.Equals(HashSaltEquals, other.HashSaltEquals)
        && System.Object.Equals(ReplicationNumEquals, other.ReplicationNumEquals)
        && System.Object.Equals(SeedNodeEquals, other.SeedNodeEquals);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + PartitionalIntervalEquals.GetHashCode();
        hashcode = (hashcode * 397) + HashSaltEquals.GetHashCode();
        hashcode = (hashcode * 397) + ReplicationNumEquals.GetHashCode();
        hashcode = (hashcode * 397) + SeedNodeEquals.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("CheckStatusResponse(");
      sb.Append(", PartitionalIntervalEquals: ");
      sb.Append(PartitionalIntervalEquals);
      sb.Append(", HashSaltEquals: ");
      sb.Append(HashSaltEquals);
      sb.Append(", ReplicationNumEquals: ");
      sb.Append(ReplicationNumEquals);
      sb.Append(", SeedNodeEquals: ");
      sb.Append(SeedNodeEquals);
      sb.Append(")");
      return sb.ToString();
    }
  }

}
