/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace Apache.IoTDB.Cluster.Rpc.Thrift
{

  public partial class GroupByRequest : TBase
  {
    private byte[] _timeFilterBytes;

    public string Path { get; set; }

    public int DataTypeOrdinal { get; set; }

    public byte[] TimeFilterBytes
    {
      get
      {
        return _timeFilterBytes;
      }
      set
      {
        __isset.timeFilterBytes = true;
        this._timeFilterBytes = value;
      }
    }

    public long QueryId { get; set; }

    public List<int> AggregationTypeOrdinals { get; set; }

    public Node Header { get; set; }

    public Node Requestor { get; set; }

    public THashSet<string> DeviceMeasurements { get; set; }


    public Isset __isset;
    public struct Isset
    {
      public bool timeFilterBytes;
    }

    public GroupByRequest()
    {
    }

    public GroupByRequest(string path, int dataTypeOrdinal, long queryId, List<int> aggregationTypeOrdinals, Node header, Node requestor, THashSet<string> deviceMeasurements) : this()
    {
      this.Path = path;
      this.DataTypeOrdinal = dataTypeOrdinal;
      this.QueryId = queryId;
      this.AggregationTypeOrdinals = aggregationTypeOrdinals;
      this.Header = header;
      this.Requestor = requestor;
      this.DeviceMeasurements = deviceMeasurements;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_path = false;
        bool isset_dataTypeOrdinal = false;
        bool isset_queryId = false;
        bool isset_aggregationTypeOrdinals = false;
        bool isset_header = false;
        bool isset_requestor = false;
        bool isset_deviceMeasurements = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Path = await iprot.ReadStringAsync(cancellationToken);
                isset_path = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                DataTypeOrdinal = await iprot.ReadI32Async(cancellationToken);
                isset_dataTypeOrdinal = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.String)
              {
                TimeFilterBytes = await iprot.ReadBinaryAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.I64)
              {
                QueryId = await iprot.ReadI64Async(cancellationToken);
                isset_queryId = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.List)
              {
                {
                  TList _list37 = await iprot.ReadListBeginAsync(cancellationToken);
                  AggregationTypeOrdinals = new List<int>(_list37.Count);
                  for(int _i38 = 0; _i38 < _list37.Count; ++_i38)
                  {
                    int _elem39;
                    _elem39 = await iprot.ReadI32Async(cancellationToken);
                    AggregationTypeOrdinals.Add(_elem39);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_aggregationTypeOrdinals = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 6:
              if (field.Type == TType.Struct)
              {
                Header = new Node();
                await Header.ReadAsync(iprot, cancellationToken);
                isset_header = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 7:
              if (field.Type == TType.Struct)
              {
                Requestor = new Node();
                await Requestor.ReadAsync(iprot, cancellationToken);
                isset_requestor = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 8:
              if (field.Type == TType.Set)
              {
                {
                  TSet _set40 = await iprot.ReadSetBeginAsync(cancellationToken);
                  DeviceMeasurements = new THashSet<string>(_set40.Count);
                  for(int _i41 = 0; _i41 < _set40.Count; ++_i41)
                  {
                    string _elem42;
                    _elem42 = await iprot.ReadStringAsync(cancellationToken);
                    DeviceMeasurements.Add(_elem42);
                  }
                  await iprot.ReadSetEndAsync(cancellationToken);
                }
                isset_deviceMeasurements = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_path)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_dataTypeOrdinal)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_queryId)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_aggregationTypeOrdinals)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_header)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_requestor)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_deviceMeasurements)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("GroupByRequest");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "path";
        field.Type = TType.String;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Path, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "dataTypeOrdinal";
        field.Type = TType.I32;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async(DataTypeOrdinal, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if (TimeFilterBytes != null && __isset.timeFilterBytes)
        {
          field.Name = "timeFilterBytes";
          field.Type = TType.String;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteBinaryAsync(TimeFilterBytes, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        field.Name = "queryId";
        field.Type = TType.I64;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(QueryId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "aggregationTypeOrdinals";
        field.Type = TType.List;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.I32, AggregationTypeOrdinals.Count), cancellationToken);
          foreach (int _iter43 in AggregationTypeOrdinals)
          {
            await oprot.WriteI32Async(_iter43, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "header";
        field.Type = TType.Struct;
        field.ID = 6;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Header.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "requestor";
        field.Type = TType.Struct;
        field.ID = 7;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Requestor.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "deviceMeasurements";
        field.Type = TType.Set;
        field.ID = 8;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteSetBeginAsync(new TSet(TType.String, DeviceMeasurements.Count), cancellationToken);
          foreach (string _iter44 in DeviceMeasurements)
          {
            await oprot.WriteStringAsync(_iter44, cancellationToken);
          }
          await oprot.WriteSetEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as GroupByRequest;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(Path, other.Path)
        && System.Object.Equals(DataTypeOrdinal, other.DataTypeOrdinal)
        && ((__isset.timeFilterBytes == other.__isset.timeFilterBytes) && ((!__isset.timeFilterBytes) || (TCollections.Equals(TimeFilterBytes, other.TimeFilterBytes))))
        && System.Object.Equals(QueryId, other.QueryId)
        && TCollections.Equals(AggregationTypeOrdinals, other.AggregationTypeOrdinals)
        && System.Object.Equals(Header, other.Header)
        && System.Object.Equals(Requestor, other.Requestor)
        && TCollections.Equals(DeviceMeasurements, other.DeviceMeasurements);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + Path.GetHashCode();
        hashcode = (hashcode * 397) + DataTypeOrdinal.GetHashCode();
        if(__isset.timeFilterBytes)
          hashcode = (hashcode * 397) + TimeFilterBytes.GetHashCode();
        hashcode = (hashcode * 397) + QueryId.GetHashCode();
        hashcode = (hashcode * 397) + TCollections.GetHashCode(AggregationTypeOrdinals);
        hashcode = (hashcode * 397) + Header.GetHashCode();
        hashcode = (hashcode * 397) + Requestor.GetHashCode();
        hashcode = (hashcode * 397) + TCollections.GetHashCode(DeviceMeasurements);
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("GroupByRequest(");
      sb.Append(", Path: ");
      sb.Append(Path);
      sb.Append(", DataTypeOrdinal: ");
      sb.Append(DataTypeOrdinal);
      if (TimeFilterBytes != null && __isset.timeFilterBytes)
      {
        sb.Append(", TimeFilterBytes: ");
        sb.Append(TimeFilterBytes);
      }
      sb.Append(", QueryId: ");
      sb.Append(QueryId);
      sb.Append(", AggregationTypeOrdinals: ");
      sb.Append(AggregationTypeOrdinals);
      sb.Append(", Header: ");
      sb.Append(Header== null ? "<null>" : Header.ToString());
      sb.Append(", Requestor: ");
      sb.Append(Requestor== null ? "<null>" : Requestor.ToString());
      sb.Append(", DeviceMeasurements: ");
      sb.Append(DeviceMeasurements);
      sb.Append(")");
      return sb.ToString();
    }
  }

}
